declare module 'niceware';
declare module 'shorthash';
declare module 'backblaze-b2';
declare module 'gun/sea';
declare module 'gun/lib/radix';
declare module 'gun/lib/radisk';
declare module 'gun/lib/store';
declare module 'gun/lib/rindexed';
declare module 'gun/lib/then';
